steps:
  # Step 1: Use a Gradle image to build the JAR
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']

  # Step 2: Copy the built JAR to the output directory
  - name: 'gcr.io/cloud-builders/cp'
    args: ['build/libs/*.jar', '/workspace/output/']

artifacts:
  objects:
    location: 'gs://jar-holder-mrig/artifacts/'
    paths:
      - 'output/*.jar'